# -- 코드를 입력하세요
# SELECT USER_ID,NICKNAME, CONCAT(CITY ,' ' ,STREET_ADDRESS1 , ' ',STREET_ADDRESS2) AS 전체주소,
# CONCAT(SUBSTRING(TLNO , 1 , 3) , '-' , SUBSTRING(TLNO , 4 , 4) , '-' , SUBSTRING(TLNO , 8 , 4)) AS 전화번호
# FROM USED_GOODS_USER AS A
# JOIN USED_GOODS_BOARD AS B
# ON B.WRITER_ID=A.USER_ID
# GROUP BY USER_ID
# HAVING COUNT(USER_ID)>=3
# ORDER BY USER_ID DESC

SELECT 
    A.USER_ID,
    A.NICKNAME, 
    CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(A.TLNO, 1, 3), '-', SUBSTRING(A.TLNO, 4, 4), '-', SUBSTRING(A.TLNO, 8, 4)) AS 전화번호
FROM 
    USED_GOODS_USER A
INNER JOIN 
    USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
GROUP BY 
    A.USER_ID, A.NICKNAME, A.CITY, A.STREET_ADDRESS1, A.STREET_ADDRESS2, A.TLNO
HAVING 
    COUNT(A.USER_ID) >= 3
ORDER BY 
    A.USER_ID DESC;
